const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#0A84FF",
    background: "#f2f2f7",
    foreground: "#0a0a0a",
    card: "#ffffff",
    cardForeground: "#0a0a0a",
    primary: "#0A84FF",
    primaryForeground: "#ffffff",
    secondary: "#e5e5ea",
    secondaryForeground: "#1c1c1e",
    muted: "#e5e5ea",
    mutedForeground: "#8e8e93",
    accent: "#e5e5ea",
    accentForeground: "#1c1c1e",
    destructive: "#ff3b30",
    destructiveForeground: "#ffffff",
    border: "#c6c6c8",
    input: "#e5e5ea",
  },
  dark: {
    text: "#ffffff",
    tint: "#0A84FF",
    background: "#000000",
    foreground: "#ffffff",
    card: "#1c1c1e",
    cardForeground: "#ffffff",
    primary: "#0A84FF",
    primaryForeground: "#ffffff",
    secondary: "#2c2c2e",
    secondaryForeground: "#ffffff",
    muted: "#2c2c2e",
    mutedForeground: "#8e8e93",
    accent: "#3a3a3c",
    accentForeground: "#ffffff",
    destructive: "#ff453a",
    destructiveForeground: "#ffffff",
    border: "#3a3a3c",
    input: "#2c2c2e",
  },
  radius: 12,
};

export default colors;
